# Any language can be specified, the ghdl scripts not depend any of them.
# (Default language is ruby on travis)
# language: python

# Specify, that we want to use docker in the docker :)
services:
  - docker

# Here are the list of run scripts of different DUTs/testcases
script:
    # Testing the installation of the ghdl
  - docker run -t ghdl/ghdl:buster-mcode ghdl --version
  
    # Mount the repo to docker, and run the hello world example
  - > 
    docker run -t -v `pwd`:/mnt/data ghdl/ghdl:buster-mcode
    /bin/bash -c  "chmod u+x /mnt/data/hello_world/hello_world.sh; /mnt/data/hello_world/hello_world.sh"
    
    # Mount the repo to docker, and run the adder example
  - >
    docker run -t -v `pwd`:/mnt/data ghdl/ghdl:buster-mcode
    /bin/bash -c  "chmod u+x /mnt/data/adder/adder.sh; /mnt/data/adder/adder.sh"
    
    # Mount the repo to docker, and run the UVVM uart example
  - >
    docker run -t -v `pwd`:/mnt/data ghdl/ghdl:buster-mcode
    /bin/bash -c  "chmod u+x /mnt/data/UVVM_scripts/*; /mnt/data/UVVM_scripts/run_all.sh"

# Notification is optional
notifications:
  email:
    on_success: never
    on_failure: always
